services:
    flask_app:
        build: .
        ports:
            - "5000:5000"
        volumes:
        - .:/workspace
        - logvolume01:/var/log
        depends_on:
            - redis
        environment:
            - FLASK_APP=my_app
            - FLASK_ENV=development
    redis:
        image: redis
volumes:
    logvolume01: {}