services:
    flask_app:
        image: flask_app
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        environment:
            - FLASK_APP=${FLASK_APP}
            - FLASK_ENV=${FLASK_ENV}
    redis:
        image: redis